import { makeAutoObservable } from "mobx";
import { fetchDatapack } from "../lib/datapack-cache";
import type { ItemGrade } from "@lineage2js/network";
import type { LANG } from "../lang/lang";
import type { BaseStats, BaseClass, RaceNames, SexNames } from "../config/character-races";

/**
 * One equipment template's stats, as generated by
 * scripts/convert-items-csv.ts -- every field optional because the source
 * only emits what a given item actually has (a shield has no P.Atk, boots
 * have no attack speed).
 */
export interface ItemStats {
  /** Weapon P.Atk / M.Atk. */
  pAtk?: number;
  mAtk?: number;
  /** Armor P.Def, and M.Def -- which jewellery carries too. */
  pDef?: number;
  mDef?: number;
  /** Shields only. */
  shieldDef?: number;
  shieldRate?: number;
  /** Evasion modifier, negative on shields. */
  evasion?: number;
  atkSpd?: number;
  crit?: number;
  /** Attack range: 40 for anything melee, up to 500+ on a bow. */
  range?: number;
  /** Accuracy modifier, fractional and often negative. */
  accuracy?: number;
  soulshots?: number;
  spiritshots?: number;
  /** Per-shot MP cost, bows and crossbows only. */
  mpConsume?: number;
  weight?: number;
  /** sword, blunt, bow, dagger, dual, pole, ... */
  weaponType?: string;
  /** light, heavy, magic, sigil. */
  armorType?: string;
  /** steel, leather, wood, ... */
  material?: string;
}

// Static reference data the wire protocol never sends as strings/codes --
// item/skill/action/class/npc/quest names, npc race/level, skill effect
// category, and system-message templates. All of it is fetch-once(-per-lang)
// and cached in memory; none of it is interactive UI state (that's UiStore).
// See App.tsx for what triggers the initial loads and re-loads on lang change.
export class DatapackStore {
  /**
   * id -> name for the current lang, see lang.ts's "item.name.<id>" special
   * case. The server never sends item name strings (ItemList/InventoryUpdate
   * are id/count/etc only) -- sourced from adrenalinebot.com's HighFive
   * database instead (public/item-names/<lang>.json), same per-language
   * caching as skillNames/actionNames/classNames.
   */
  itemNames: Record<string, string> = {};
  private itemNamesCache: Partial<Record<LANG, Record<string, string>>> = {};
  /**
   * id -> name for the current lang, see lang.ts's "skill.name.<id>" special
   * case. The server never sends skill name strings (SkillList/
   * AcquireSkillInfo are id/level only) -- sourced from adrenalinebot.com's
   * HighFive database instead (public/skill-names/<lang>.json), same
   * per-language caching as actionNames/classNames.
   */
  skillNames: Record<string, string> = {};
  private skillNamesCache: Partial<Record<LANG, Record<string, string>>> = {};
  /** id -> name for the current lang, see lang.ts's "action.name.<id>" special case. Same source/caching as itemNames/skillNames. */
  actionNames: Record<string, string> = {};
  private actionNamesCache: Partial<Record<LANG, Record<string, string>>> = {};
  /** classId -> name for the current lang (public/class-names/<lang>.json, sourced from adrenalinebot.com's HighFive database -- see class-tree.ts's getClassLabel()). Same per-language caching as actionNames. */
  classNames: Record<string, string> = {};
  private classNamesCache: Partial<Record<LANG, Record<string, string>>> = {};
  /**
   * npcId -> name for the current lang, see config/npc-name-mapping.ts's
   * getNpcName(). Only used as a fallback when NpcInfo's own wire name comes
   * back empty (some templates deliberately omit it, see NpcInfo.ts) --
   * sourced from adrenalinebot.com's HighFive database, same per-language
   * caching as itemNames/skillNames.
   */
  npcNames: Record<string, string> = {};
  private npcNamesCache: Partial<Record<LANG, Record<string, string>>> = {};
  /**
   * npcId -> title ("Blacksmith", ...) for the current lang, see
   * config/npc-title-mapping.ts. Same gap as npcNames -- NpcInfo's title
   * field is deliberately sent empty and the retail client resolves it from
   * its own table. Unlike every other table here it is *not* from
   * adrenalinebot.com, which has no title data: en.json is lineage2ts's own
   * npcProperties.csv, and ru.json is that run through a hand-written
   * 474-entry translation table (scripts/npc-titles-ru.ts), since no
   * localized source exists -- no RU client ships an NpcName-ru.dat to read
   * the official strings out of. Town names in it are at least the real
   * localization, lifted from item-names/ru.json's Scroll of Escape entries.
   */
  npcTitles: Record<string, string> = {};
  private npcTitlesCache: Partial<Record<LANG, Record<string, string>>> = {};
  /** npcId -> race code (e.g. "UNDEAD"), see config/npc-race-mapping.ts. Not localized -- these are enum codes, not display strings. */
  npcRaces: Record<string, string> = {};
  private npcRacesRequested = false;
  /** npcId -> level, see config/npc-level-mapping.ts. Same datapack source/gap as npcRaces -- NpcInfo never sends a monster's level over the wire. */
  npcLevels: Record<string, number> = {};
  private npcLevelsRequested = false;
  /**
   * itemId -> grade, see config/item-mapping.ts's getItemGradeLabel(). Same
   * datapack source/gap as npcRaces -- no item packet (ItemList/
   * InventoryUpdate/TradeStart/...) ever sends grade/crystal_type over the
   * wire (confirmed against lineage2ts's and L2J_Mobius's writeItem, see
   * TODO.md). Source data (public/item-grades/data.json) is grouped by grade
   * ({ [gradeIndex]: itemId[] }, far fewer grades than items) and inverted
   * into this id->grade lookup once at load time.
   */
  itemGrades: Record<string, ItemGrade> = {};
  private itemGradesRequested = false;
  /**
   * itemId -> combat stats for equipment, see config/item-mapping.ts's
   * getItemStatLines(). Same datapack gap as itemGrades, and for the same
   * reason: an item packet carries an item *instance* (object id, template
   * id, count, enchant, augmentation, attributes) and never what the
   * template is worth in a fight, so P.Atk/P.Def/attack speed/... have to
   * come from a local table. Generated from lineage2ts's own item CSV by
   * scripts/convert-items-csv.ts; equipment only, and only the fields that
   * are non-zero on a given item.
   */
  itemStats: Record<string, ItemStats> = {};
  private itemStatsRequested = false;
  /** skillId -> [magicClass, operateType, isDebuff], see config/skill-effect-mapping.ts and @lineage2js/network's EffectCategory.ts. Same datapack source/gap as npcRaces -- AbnormalStatusUpdate never sends a buff's category over the wire. */
  skillEffectFields: Record<string, [number, string, number]> = {};
  private skillEffectFieldsRequested = false;
  /**
   * race -> baseClass -> sex -> starting STR/DEX/CON/INT/WIT/MEN, see
   * config/character-races.ts's getBaseStats(). Sourced from L2J_Mobius's
   * HighFive datapack (dist/game/data/stats/chars/baseStats/<ClassName>.xml's
   * base* fields, one file per starting classId) -- only used as the
   * char-create preview's fallback before the real server-provided
   * CharacterTemplate list loads (see network-mapping.ts's getTemplateStats()),
   * so it's keyed by our own RaceNames/BaseClass/SexNames rather than the wire's
   * numeric classId. MALE/FEMALE duplicate the same values for every race
   * except Kamael, where the two starting classes (Male/Female Soldier)
   * genuinely differ. Not exhaustive: Dwarf/Kamael have no "mystic" entry
   * since neither race offers a mystic starting class.
   */
  characterBaseStats: Partial<Record<RaceNames, Partial<Record<BaseClass, Record<SexNames, BaseStats>>>>> = {};
  private characterBaseStatsRequested = false;
  /** questId -> name for the current lang, see config/quest-mapping.ts's getQuestName(). Forward-looking -- no quest window built yet. Same source/caching as itemNames/skillNames. */
  questNames: Record<string, string> = {};
  private questNamesCache: Partial<Record<LANG, Record<string, string>>> = {};
  /**
   * messageId -> template string ("$s1"/"$c1" placeholders) for the current
   * lang, see config/system-message-mapping.ts. Only en.json has the full
   * ~3236-entry L2J_Mobius-sourced table; other languages are a curated,
   * hand-translated subset (currently just the battle-log whitelist) that
   * gets merged on top of the English base, so anything untranslated still
   * falls back to English instead of a raw "#123".
   */
  systemMessages: Record<string, string> = {};
  private systemMessagesCache: Partial<Record<LANG, Record<string, string>>> = {};

  constructor() {
    makeAutoObservable(this);
  }

  /** Reloads every per-language table for `lang` -- call whenever UiStore.lang changes (see App.tsx). */
  loadForLang(lang: LANG) {
    this.loadActionNames(lang);
    this.loadClassNames(lang);
    this.loadSkillNames(lang);
    this.loadItemNames(lang);
    this.loadNpcNames(lang);
    this.loadNpcTitles(lang);
    this.loadQuestNames(lang);
    this.loadSystemMessages(lang);
  }

  setItemNames(names: Record<string, string>) {
    this.itemNames = names;
  }

  /** Fetches public/item-names/<lang>.json for `lang`, caching each language in memory once loaded -- same treatment as loadActionNames(). */
  async loadItemNames(lang: LANG) {
    const cached = this.itemNamesCache[lang];
    if (cached) {
      this.setItemNames(cached);
      return;
    }
    try {
      const response = await fetchDatapack(`item-names/${lang}.json`);
      const names: Record<string, string> = await response.json();
      this.itemNamesCache[lang] = names;
      this.setItemNames(names);
    } catch {
      // leave itemNames as-is -- t() falls back to the raw "item.name.<id>" key
    }
  }

  setSkillNames(names: Record<string, string>) {
    this.skillNames = names;
  }

  /** Fetches public/skill-names/<lang>.json for `lang`, caching each language in memory once loaded -- same treatment as loadActionNames(). */
  async loadSkillNames(lang: LANG) {
    const cached = this.skillNamesCache[lang];
    if (cached) {
      this.setSkillNames(cached);
      return;
    }
    try {
      const response = await fetchDatapack(`skill-names/${lang}.json`);
      const names: Record<string, string> = await response.json();
      this.skillNamesCache[lang] = names;
      this.setSkillNames(names);
    } catch {
      // leave skillNames as-is -- t() falls back to the raw "skill.name.<id>" key
    }
  }

  setActionNames(names: Record<string, string>) {
    this.actionNames = names;
  }

  /** Fetches public/action-names/<lang>.json for `lang`, caching each language in memory once loaded. */
  async loadActionNames(lang: LANG) {
    const cached = this.actionNamesCache[lang];
    if (cached) {
      this.setActionNames(cached);
      return;
    }
    try {
      const response = await fetchDatapack(`action-names/${lang}.json`);
      const names: Record<string, string> = await response.json();
      this.actionNamesCache[lang] = names;
      this.setActionNames(names);
    } catch {
      // leave actionNames as-is -- t() falls back to the raw "action.name.<id>" key
    }
  }

  setClassNames(names: Record<string, string>) {
    this.classNames = names;
  }

  /** Fetches public/class-names/<lang>.json for `lang`, caching each language in memory once loaded -- same treatment as loadActionNames(). */
  async loadClassNames(lang: LANG) {
    const cached = this.classNamesCache[lang];
    if (cached) {
      this.setClassNames(cached);
      return;
    }
    try {
      const response = await fetchDatapack(`class-names/${lang}.json`);
      const names: Record<string, string> = await response.json();
      this.classNamesCache[lang] = names;
      this.setClassNames(names);
    } catch {
      // leave classNames as-is -- getClassLabel() falls back to deriving from the ClassId enum key
    }
  }

  setNpcNames(names: Record<string, string>) {
    this.npcNames = names;
  }

  /** Fetches public/npc-names/<lang>.json for `lang`, caching each language in memory once loaded -- same treatment as loadActionNames(). */
  async loadNpcNames(lang: LANG) {
    const cached = this.npcNamesCache[lang];
    if (cached) {
      this.setNpcNames(cached);
      return;
    }
    try {
      const response = await fetchDatapack(`npc-names/${lang}.json`);
      const names: Record<string, string> = await response.json();
      this.npcNamesCache[lang] = names;
      this.setNpcNames(names);
    } catch {
      // leave npcNames as-is -- getNpcName() falls back to the "Mob #<id>"/"NPC #<id>" placeholder
    }
  }

  setQuestNames(names: Record<string, string>) {
    this.questNames = names;
  }

  /** Fetches public/quest-names/<lang>.json for `lang`, caching each language in memory once loaded -- same treatment as loadActionNames(). */
  async loadQuestNames(lang: LANG) {
    const cached = this.questNamesCache[lang];
    if (cached) {
      this.setQuestNames(cached);
      return;
    }
    try {
      const response = await fetchDatapack(`quest-names/${lang}.json`);
      const names: Record<string, string> = await response.json();
      this.questNamesCache[lang] = names;
      this.setQuestNames(names);
    } catch {
      // leave questNames as-is -- getQuestName() falls back to "Quest #<id>"
    }
  }

  setNpcRaces(races: Record<string, string>) {
    this.npcRaces = races;
  }

  /**
   * Fetches public/npc-races/data.json once, same treatment as
   * loadItemNames(). Built from L2J_Mobius's HighFive datapack (dist/game/
   * data/stats/npcs/*.xml's <race> per npc id) -- the wire protocol never
   * sends a monster's race, only its template id (see NpcInfo.ts).
   */
  async loadNpcRaces() {
    if (this.npcRacesRequested) return;
    this.npcRacesRequested = true;
    try {
      const response = await fetchDatapack(`npc-races/data.json`);
      const races: Record<string, string> = await response.json();
      this.setNpcRaces(races);
    } catch {
      this.npcRacesRequested = false;
    }
  }

  setNpcTitles(titles: Record<string, string>) {
    this.npcTitles = titles;
  }

  /** Fetches public/npc-titles/<lang>.json for `lang`, caching each language in memory once loaded -- same treatment as loadNpcNames(). */
  async loadNpcTitles(lang: LANG) {
    const cached = this.npcTitlesCache[lang];
    if (cached) {
      this.setNpcTitles(cached);
      return;
    }
    try {
      const response = await fetchDatapack(`npc-titles/${lang}.json`);
      const titles: Record<string, string> = await response.json();
      this.npcTitlesCache[lang] = titles;
      this.setNpcTitles(titles);
    } catch {
      // leave npcTitles as-is -- an npc just shows its name with no title line
    }
  }

  setNpcLevels(levels: Record<string, number>) {
    this.npcLevels = levels;
  }

  /** Fetches public/npc-levels/data.json once, same source/treatment as loadNpcRaces(). */
  async loadNpcLevels() {
    if (this.npcLevelsRequested) return;
    this.npcLevelsRequested = true;
    try {
      const response = await fetchDatapack(`npc-levels/data.json`);
      const levels: Record<string, number> = await response.json();
      this.setNpcLevels(levels);
    } catch {
      this.npcLevelsRequested = false;
    }
  }

  setItemGrades(grades: Record<string, ItemGrade>) {
    this.itemGrades = grades;
  }

  /** Fetches public/item-grades/data.json once, same treatment as loadNpcRaces() -- inverts the grouped-by-grade source shape into an id->grade lookup. */
  async loadItemGrades() {
    if (this.itemGradesRequested) return;
    this.itemGradesRequested = true;
    try {
      const response = await fetchDatapack(`item-grades/data.json`);
      const byGrade: Record<string, number[]> = await response.json();
      const grades: Record<string, ItemGrade> = {};
      for (const [gradeIndex, itemIds] of Object.entries(byGrade)) {
        for (const id of itemIds) {
          grades[id] = Number(gradeIndex) as ItemGrade;
        }
      }
      this.setItemGrades(grades);
    } catch {
      this.itemGradesRequested = false;
    }
  }

  setItemStats(stats: Record<string, ItemStats>) {
    this.itemStats = stats;
  }

  /** Fetches public/item-stats/data.json once, same treatment as loadItemGrades() -- already keyed by item id, so no inversion needed. */
  async loadItemStats() {
    if (this.itemStatsRequested) return;
    this.itemStatsRequested = true;
    try {
      const response = await fetchDatapack(`item-stats/data.json`);
      this.setItemStats(await response.json());
    } catch {
      this.itemStatsRequested = false;
    }
  }

  setSkillEffectFields(fields: Record<string, [number, string, number]>) {
    this.skillEffectFields = fields;
  }

  /**
   * Fetches public/skill-effect-fields/data.json once, same treatment as
   * loadNpcRaces(). Generated from lineage2ts's own datapack CSV
   * (cli/overrides/data/csv/skills/skills.csv's magicClass/operateType/
   * isDebuff columns, one row per skill id -- taking each id's lowest-level
   * row, since a handful of ids reuse high "levels" for unrelated skill
   * variants, e.g. Spoil's levels 101+).
   */
  async loadSkillEffectFields() {
    if (this.skillEffectFieldsRequested) return;
    this.skillEffectFieldsRequested = true;
    try {
      const response = await fetchDatapack(`skill-effect-fields/data.json`);
      const fields: Record<string, [number, string, number]> = await response.json();
      this.setSkillEffectFields(fields);
    } catch {
      this.skillEffectFieldsRequested = false;
    }
  }

  setCharacterBaseStats(stats: Partial<Record<RaceNames, Partial<Record<BaseClass, Record<SexNames, BaseStats>>>>>) {
    this.characterBaseStats = stats;
  }

  /** Fetches public/character-base-stats/data.json once, same treatment as loadNpcRaces(). */
  async loadCharacterBaseStats() {
    if (this.characterBaseStatsRequested) return;
    this.characterBaseStatsRequested = true;
    try {
      const response = await fetchDatapack(`character-base-stats/data.json`);
      const stats: Partial<Record<RaceNames, Partial<Record<BaseClass, Record<SexNames, BaseStats>>>>> = await response.json();
      this.setCharacterBaseStats(stats);
    } catch {
      this.characterBaseStatsRequested = false;
    }
  }

  setSystemMessages(messages: Record<string, string>) {
    this.systemMessages = messages;
  }

  /**
   * Fetches the English base table plus `lang`'s translated subset (skipped
   * for English itself), merges them (translated entries win, everything
   * else stays English), and caches the merged result per language so
   * switching languages doesn't re-fetch every time.
   */
  async loadSystemMessages(lang: LANG) {
    const cached = this.systemMessagesCache[lang];
    if (cached) {
      this.setSystemMessages(cached);
      return;
    }
    try {
      const enResponse = await fetchDatapack(`system-messages/en.json`);
      const en: Record<string, string> = await enResponse.json();
      let merged = en;
      if (lang !== "en") {
        try {
          const langResponse = await fetchDatapack(`system-messages/${lang}.json`);
          const overrides: Record<string, string> = await langResponse.json();
          merged = { ...en, ...overrides };
        } catch {
          // no translation file for this lang yet -- English fallback for everything
        }
      }
      this.systemMessagesCache[lang] = merged;
      this.setSystemMessages(merged);
    } catch {
      // leave systemMessages as-is -- formatSystemMessage falls back to "#<id>"
    }
  }
}
