import { rootStore } from "../stores/RootStore";
import { getItemName } from "./item-mapping";
import { getSkillName } from "./skill-mapping";

// Wire type tags from AbstractMessagePacket.ts (network package) -- kept in
// sync manually since the network package doesn't export them as a value.
const TYPE_TEXT = 0;
const TYPE_INT_NUMBER = 1;
const TYPE_NPC_NAME = 2;
const TYPE_ITEM_NAME = 3;
const TYPE_SKILL_NAME = 4;
const TYPE_CASTLE_NAME = 5;
const TYPE_LONG_NUMBER = 6;
const TYPE_ZONE_NAME = 7;
const TYPE_ELEMENT_NAME = 9;
const TYPE_INSTANCE_NAME = 10;
const TYPE_DOOR_NAME = 11;
const TYPE_PLAYER_NAME = 12;
const TYPE_SYSTEM_STRING = 13;

// Reactive read, not a stored field: UiStore.systemMessages loads
// asynchronously (see UiStore.loadSystemMessages()), same treatment as
// item-mapping.ts's getItemName(). The wire itself never sends message
// text, only numeric ids (see AbstractMessagePacket.ts) -- UiStore merges
// the English base table with the current lang's translated subset, so
// this already reflects the active language.
export function getSystemMessageTemplate(messageId: number): string | undefined {
  return rootStore.ui.systemMessages[messageId];
}

// Resolves one positional param to display text, based on its wire type tag.
// Types without a real lookup table here (npc/castle/instance/door/element
// names) fall back to a bracketed numeric id, same placeholder convention
// NpcInfo.ts already uses for unresolved npc names.
function formatParam(value: unknown, type: number | undefined): string {
  switch (type) {
    case TYPE_TEXT:
    case TYPE_PLAYER_NAME:
      return String(value);
    case TYPE_ITEM_NAME:
      return getItemName({ Id: value as number });
    case TYPE_SKILL_NAME: {
      const [skillId] = value as [number, number];
      return getSkillName({ Id: skillId });
    }
    case TYPE_ZONE_NAME: {
      const [x, y, z] = value as [number, number, number];
      return `(${x}, ${y}, ${z})`;
    }
    case TYPE_NPC_NAME:
      return `NPC #${value}`;
    case TYPE_CASTLE_NAME:
      return `Castle #${value}`;
    case TYPE_INSTANCE_NAME:
      return `Instance #${value}`;
    case TYPE_DOOR_NAME:
      return `Door #${value}`;
    case TYPE_ELEMENT_NAME:
      return `Element #${value}`;
    case TYPE_SYSTEM_STRING:
      return getSystemMessageTemplate(value as number) ?? `#${value}`;
    case TYPE_INT_NUMBER:
    case TYPE_LONG_NUMBER:
    default:
      return String(value);
  }
}

// Substitutes a template's $s1/$c1/... placeholders -- the letter is just a
// semantic hint (s=generic, c=character-like); both share one positional
// index space straight into params[]/paramTypes[] (1-based in the template).
export function formatSystemMessage(messageId: number, params: unknown[], paramTypes: number[]): string {
  const template = getSystemMessageTemplate(messageId);
  if (!template) {
    return `#${messageId}`;
  }
  return template.replace(/\$[sc](\d+)/g, (match, indexStr: string) => {
    const index = Number(indexStr) - 1;
    if (index < 0 || index >= params.length) {
      return match;
    }
    return formatParam(params[index], paramTypes[index]);
  });
}

/**
 * Message ids from feature areas that don't belong in a general system-
 * message log -- private store/warehouse/mail, friends list, clan war/
 * pledge/clan hall, siege/fortress/castle/territory, olympiad/hero,
 * petitions/GM, macros, command channel/party room, recipe/multisell,
 * item auction, fishing/manor/seed/crop, cursed weapons, henna, seven
 * signs, mentor, tutorial, daily missions, PC cafe. None of those are
 * implemented in this client yet, but the server can still broadcast
 * world-wide instances of them (e.g. a siege starting) regardless of what
 * the local player is doing.
 *
 * Generated by keyword-matching the constant names in L2J_Mobius's
 * SystemMessageId.java (gitlab.com/MobiusDevelopment/L2J_Mobius,
 * L2J_Mobius_CT_2.6_HighFive/java/org/l2jmobius/gameserver/network/
 * SystemMessageId.java) against the category list above -- 661 of 3236
 * total ids. Everything not listed here shows by default in
 * system-messages.window.tsx.
 */
const NOISY_SYSTEM_MESSAGE_IDS = new Set<number>([
  13, 14, 15, 16, 17, 18, 19, 130, 132, 133, 134, 150, 162, 165, 166, 167, 168, 169, 170, 171,
  220, 221, 227, 240, 245, 250, 258, 260, 265, 266, 273, 282, 288, 289, 291, 292, 294, 295, 307, 311,
  312, 334, 340, 349, 358, 359, 360, 381, 382, 383, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394,
  395, 404, 406, 407, 415, 425, 464, 468, 469, 470, 471, 473, 475, 477, 478, 479, 480, 481, 482, 484,
  485, 486, 487, 491, 492, 494, 502, 503, 504, 505, 506, 507, 508, 509, 510, 512, 514, 515, 516, 517,
  518, 519, 520, 523, 524, 525, 526, 527, 549, 550, 554, 577, 599, 601, 602, 605, 606, 613, 615, 617,
  618, 619, 620, 622, 623, 625, 629, 634, 635, 636, 638, 639, 640, 641, 644, 645, 646, 647, 658, 659,
  660, 662, 663, 665, 666, 667, 668, 669, 673, 674, 675, 676, 678, 680, 681, 684, 685, 688, 689, 690,
  691, 693, 702, 703, 704, 706, 707, 708, 709, 710, 711, 712, 718, 721, 722, 723, 724, 725, 730, 731,
  732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 751, 761, 763, 776, 777,
  780, 782, 792, 793, 797, 801, 802, 803, 805, 808, 810, 819, 827, 828, 837, 838, 839, 840, 841, 842,
  843, 844, 845, 846, 847, 852, 853, 856, 859, 862, 871, 872, 874, 879, 882, 883, 884, 885, 886, 888,
  889, 890, 893, 894, 895, 896, 903, 904, 924, 933, 934, 935, 937, 958, 959, 960, 971, 1004, 1005, 1037,
  1038, 1039, 1041, 1043, 1051, 1052, 1053, 1056, 1058, 1060, 1061, 1063, 1065, 1078, 1114, 1124, 1128, 1132, 1135, 1176,
  1178, 1180, 1189, 1190, 1194, 1199, 1200, 1202, 1203, 1205, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219,
  1222, 1228, 1231, 1233, 1234, 1235, 1238, 1240, 1241, 1250, 1251, 1253, 1255, 1257, 1259, 1260, 1261, 1262, 1263, 1271,
  1272, 1273, 1274, 1294, 1296, 1297, 1301, 1302, 1305, 1328, 1329, 1330, 1331, 1339, 1341, 1343, 1363, 1364, 1370, 1388,
  1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1413, 1447, 1448, 1453, 1458, 1460, 1462, 1463, 1470, 1471, 1472,
  1479, 1480, 1483, 1484, 1490, 1491, 1492, 1500, 1501, 1503, 1505, 1506, 1507, 1508, 1509, 1516, 1528, 1529, 1544, 1551,
  1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1569, 1574, 1578, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587,
  1588, 1589, 1591, 1592, 1593, 1594, 1602, 1603, 1605, 1608, 1616, 1617, 1638, 1639, 1640, 1641, 1642, 1651, 1657, 1658,
  1662, 1663, 1670, 1673, 1675, 1677, 1678, 1679, 1682, 1683, 1684, 1686, 1688, 1691, 1692, 1693, 1694, 1695, 1704, 1705,
  1706, 1707, 1708, 1711, 1712, 1717, 1719, 1723, 1728, 1729, 1750, 1772, 1773, 1774, 1776, 1778, 1779, 1780, 1784, 1786,
  1823, 1824, 1825, 1826, 1829, 1830, 1831, 1832, 1834, 1841, 1845, 1856, 1857, 1858, 1869, 1870, 1891, 1898, 1900, 1911,
  1919, 1972, 1977, 2013, 2014, 2017, 2018, 2020, 2024, 2025, 2026, 2029, 2041, 2046, 2047, 2075, 2083, 2084, 2085, 2087,
  2088, 2089, 2090, 2103, 2126, 2131, 2143, 2158, 2159, 2160, 2169, 2172, 2173, 2179, 2180, 2181, 2183, 2184, 2192, 2198,
  2223, 2227, 2231, 2233, 2234, 2238, 2239, 2240, 2241, 2242, 2243, 2250, 2255, 2276, 2324, 2328, 2334, 2349, 2352, 2378,
  2389, 2393, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2470, 2471, 2508, 2509, 2567, 2572, 2590, 2591, 2708, 2709, 2710,
  2711, 2712, 2732, 2737, 2750, 2754, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2776, 2788, 2789, 2790,
  2791, 2794, 2795, 2796, 2797, 2798, 2799, 2840, 2900, 2901, 2902, 2903, 2904, 2911, 2913, 2914, 2915, 2918, 2919, 2924,
  2936, 2937, 2938, 2941, 2955, 2956, 2967, 2968, 2969, 2993, 2994, 2995, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003,
  3006, 3008, 3009, 3010, 3011, 3012, 3014, 3015, 3019, 3020, 3025, 3029, 3030, 3033, 3034, 3050, 3064, 3066, 3067, 3068,
  3069, 3072, 3077, 3082, 3084, 3087, 3094, 3124, 3128, 3129, 3130, 3170, 3173, 3174, 3193, 6049, 6058, 6059, 6061, 6062,
  6063,
]);

export function isNoisySystemMessage(messageId: number): boolean {
  return NOISY_SYSTEM_MESSAGE_IDS.has(messageId);
}
